services:
  db:
    image: postgres:14.6-alpine
    container_name: postgres-initial
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres-initial}
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - '${DB_PORT:-5431}:5432'
